title: GMTL
logo:
description: 'This is the detail page of the paper <br><strong><em>GMTL: A GART Based Multi-task Learning Model for Multi-Social-Temporal Prediction in Online Games.</em></strong>'
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
paper_link: /tree/master/docs/GMTL.pdf
data_link: /tree/master/data
